

services:
  mysql:
    image: mysql:8
    container_name: event-manager-mysql
    restart: always
    environment:
      MYSQL_DATABASE: event-launch-db
      MYSQL_USER: admin
      MYSQL_PASSWORD: f1r3wall@123
      MYSQL_ROOT_PASSWORD: root_password_123 # Change this to a secure root password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
